### ISSUE TITLE
NSIS Installation directions

### ISSUE THREAD

**Issue by bparbhu** [negrutiu/nsis-nscurl#1]
Hi @negrutiu ,

I would like to use this with a current NSIS installer I'm working on, though I'm not sure if this is installed as a plugin in that I'm looking for dll files and .nsh files. If you can could you provide a set of instructions for NSIS newbs like myself.

Thanks again and much appreciated.

-Brian

**Comment by negrutiu** [comment]
Hi @bparbhu,
I've just written a [getting-started wiki page](https://github.com/negrutiu/nsis-nscurl/wiki/Getting-Started) that sheds more light on this topic...

**Short answer**:  
NScurl is a 3rd party plugin, it's not included in the official NSIS distro. You'll need to download/compile the latest binary (NScurl.dll) and call it in your NSIS script... Once your installer (Setup.exe) gets built, NScurl.dll is automatically embedded inside it and called at runtime.

Alternatively, I've started an [NSIS fork project](https://github.com/negrutiu/nsis) that includes NScurl as built-in plugin. You may want to check it out...

**Comment by bparbhu** [comment]
Thanks for the clarification @negrutiu , I appreciate it. Actually I'm trying to get a hold of people from the NSIS community to ask advice about developing installers within NSIS and I'm having trouble finding a good forum or place. Do you have any suggestions?
