### ISSUE TITLE
Incorrect plugin_api_version check

### ISSUE THREAD

**Issue by whindsaks** [negrutiu/nsis-nscurl#14]
From the official NSIS api.h

 > When doing version checks, always remember to use >=, ex: if (pX->exec_flags->plugin_api_version >= NSISPIAPIVER_1_0)

`BOOL RegisterPluginCallbackIsValid = pX->exec_flags->plugin_api_version >= NSISPIAPIVER_1_0;`

**Comment by whindsaks** [comment]
Your change is still wrong, the correct check is `plugin_api_version >= NSISPIAPIVER_1_0`. Don't use NSISPIAPIVER_CURR.

**Comment by negrutiu** [comment]
I disagree.
If my project gets built in the future against NSIS API 2.0 for example, I'd prefer the output binary to load only in 2.0+ environments. I wouldn't want to hard code a specific version number.
`NSISPIAPIVER_CURR` points to the correct value depending on the NSIS SDK you build with.

Thanks for spotting the problem, btw

**Comment by whindsaks** [comment]
If NSISPIAPIVER_CURR ever gets to 2.0, chances are your code would not compile in the first place.

There is an ABI guarantee that the members already there will not change in 1.x, only new ones can be added at the end which is why you should not compare with _CURR.

**Comment by negrutiu** [comment]
I still think that using NSISPIAPIVER_CURR is the safest way to go.
If there'll ever be a 2.0, this project may or may not compile, backward compatibility may or may not be preserved... who knows? We can reevaluate the version check if/when we get there
