### ISSUE TITLE
NScurl::http GET is generating empty directories with single character name as first character of download path 

### ISSUE THREAD

**Issue by fjwbarnard** [negrutiu/nsis-nscurl#16]
![image](https://github.com/negrutiu/nsis-nscurl/assets/20688586/7ac53a82-83be-4773-99ba-e2ab711e0f8f)

The empty directories indicated are named according to the first character of the downloaded files. In this case, only the `locales` directory was expected, and itself contains the same situation:
![image](https://github.com/negrutiu/nsis-nscurl/assets/20688586/5f78e0df-e1fa-4d72-81cf-2d85caa3d12d)

This is using NScurl v1.2024.4.6 x86-unicode

**Comment by fjwbarnard** [comment]
When enabling `/DEBUG nsCurl-debugDownload.log` a corresponding directory is created for that file as well:
![image](https://github.com/negrutiu/nsis-nscurl/assets/20688586/92616ae2-847d-4bbc-b23e-119f6bcab4b1)

**Comment by negrutiu** [comment]
This looks like a faulty handling of relative file paths.
Could you try using full destination paths and see how it goes?

For example `$INSTDIR\chrome_100_percent.pak` instead of `chrome_100_percent.pak`
...and same for `/DEBUG "$INSTDIR\nsCurl-debugDownload.log`

**Comment by fjwbarnard** [comment]
OK confirmed using $INSTDIR\ prefixed to the download path works as expected without the random directories being created

**Comment by negrutiu** [comment]
Awesome.
I'll fix the original issue in the next release. Thanks for reporting!

**Comment by fjwbarnard** [comment]
> Awesome. I'll fix the original issue in the next release. Thanks for reporting!

Great, thanks for the plugin and the fast feedback!

**Comment by negrutiu** [comment]
Issue fixed in [nscurl/1.2024.4.30](https://github.com/negrutiu/nsis-nscurl/releases/tag/v1.2024.4.30)
Using relative file names should work now
