### ISSUE TITLE
Have plan to support download file by ftp?

### ISSUE THREAD

**Issue by halx99** [negrutiu/nsis-nscurl#2]
Curl suppot ftp file download, but when I test NScurl, it can't download file via ftp url, so do you have any plan to support it?

**Comment by negrutiu** [comment]
Nope, sorry.
I have no plans to add support for FTP (or any other protocols) in the near future.

**Comment by halx99** [comment]
Thanks, and you already provide prebuilt curl library which support all protocols, I just change link and works well.

Edit:
I have done at my fork and create minimal NScurl.dll  for file download purpose only: https://github.com/simdsoft/nsis-nscurl/releases/tag/v1.2022.1.7_minimal
