### ISSUE TITLE
Have an option to use Windows truststore

### ISSUE THREAD

**Issue by cgs-lbergeron** [negrutiu/nsis-nscurl#28]
From my understanding, libcurl allows the use of Windows trustore with this option : CURLSSLOPT_NATIVE_CA
https://curl.se/libcurl/c/CURLOPT_SSL_OPTIONS.html

It would be a very welcomed addition if we could have an additional parameter to enable this.

Unless there is another way to do it ?

**Comment by negrutiu** [comment]
Excellent idea. I'll put it on the todo list 👍🏻

**Comment by negrutiu** [comment]
Implemented in [v24.8.5.108](https://github.com/negrutiu/nsis-nscurl/releases/tag/v24.8.5.108)
It's worth mentioning that the new option is __active__ by default. By default, both the built-in `cacert.pem` and Windows CA store are used for SSL validation.
You're free to disable either of them by using `/CACERT none` and/or `/CASTORE false`
