### ISSUE TITLE
Error setting certificate verify locations when Windows username contains non-latin characters

### ISSUE THREAD

**Issue by deiteris** [negrutiu/nsis-nscurl#3]
Hello 👋 

First of all, thank you for this awesome plugin!

I've recently found an issue, when CAfile path was unable to set up when the Windows username contains non-latin characters (happened with Korean and Chinese usernames).

Here's the error occurring in the installer I'm working on when attempting to download a file over HTTPS.
![image](https://user-images.githubusercontent.com/6103913/152501509-924bbdf1-fdf8-4ee0-afb9-2a062ddf38e1.png)

The code I'm using to download:
```
NScurl::http GET "https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.14%2B9/OpenJDK11U-jre_x64_windows_hotspot_11.0.14_9.zip" "$TEMP\OpenJDK11U-jre_x64_windows_hotspot_11.0.14_9.zip" /CANCEL /RESUME /END
```

Full error message is: `0x4d "error setting certificate verify locations:  CAfile: C:\Users\ CApath: none".`.

**Comment by negrutiu** [comment]
Thanks for reporting the issue.
It's strange though... I'm not able to reproduce it.
This plugin is used extensively in Unicode locales and never heard about such error.

Nevertheless, I've made a change that was on my list for some time...
The builtin `cacert.pem` is no longer extracted to disk, but used directly from memory.
Unicode paths should not be a problem now.
Please give it a try and let me know what happens.

Also, in your script make sure:
- You're actually building an Unicode installer.  
Declare either `Unicode true` or `Target x86-unicode` early in your script.
- Call `InitPluginsDir` in your `.onInit` function.

**Comment by deiteris** [comment]
Thanks. I'll ask the users who experience this issue to try this out and see if it helps :) For me it works as intended.

It might be because I didn't call `InitPluginsDir`, but I did use `Unicode true` (and NSIS 3.0.8 uses it by default as well).

**Comment by deiteris** [comment]
Can confirm that this issue no longer occurs. Thanks!

**Comment by negrutiu** [comment]
That's awesome. Thanks again for reporting
