### ISSUE TITLE
Proxy auth not working

### ISSUE THREAD

**Issue by shengalts** [negrutiu/nsis-nscurl#38]
Trying to download file via proxy: /AUTH "proxyTestUser" "proxyTestPass" /PROXY "http://192.168.1.36:8080" and get "407 Proxy Authentication Required".
In source you use CURLOPT_USERNAME and CURLOPT_PASSWORD for /AUTH variables, but for proxy /AUTH must be CURLOPT_PROXYUSERNAME and CURLOPT_PROXYPASSWORD. May be add new parameter,  for example,  /PROXYAUTH?

Very good plugin since inetc not always do the deal!

**Comment by shengalts** [comment]
Simple patch to fix support of proxy authentication - added /PROXYAUTH parameter.

[proxy.patch](https://github.com/user-attachments/files/18157341/proxy.patch)

**Comment by negrutiu** [comment]
Thank you @shengalts for the patch and for your patience :)
I've included your changes in a new branch and built it here: https://github.com/negrutiu/nsis-nscurl/actions/runs/12390850452
Could you please [give it a try](https://github.com/negrutiu/nsis-nscurl/actions/runs/12390850452/artifacts/2336831665) and see how it goes?

I'm unable to set up a working proxy with auth... still trying...

**Comment by shengalts** [comment]
Working great! Thanks for your work!

**Comment by shengalts** [comment]
>  I'm unable to set up a working proxy with auth... still trying...

For proxy test I use tiny program:
https://3proxy.ru/download/

3proxy.cfg example:
```
service
internal 192.168.1.36
#external 192.168.1.1
nserver 192.168.1.1
nscache 65536

flush
auth strong
users proxyTestUser:CL:proxyTestPass

proxy -p8080

end
```

And run it with command: `3proxy.exe 3proxy.cfg`
