### ISSUE TITLE
question, TIMEREMAINING

### ISSUE THREAD

**Issue by shimon128** [negrutiu/nsis-nscurl#4]
Is it possible to see in real time during the download how much time has passed in the download and how much time is left?

/RETURN "@TIMEELAPSED@ - @TIMEREMAINING@"

**Comment by negrutiu** [comment]
Of course.
You may want to play around with `/string TEXT "[@PERCENT@%] @OUTFILE@, @TIMEELAPSED@ / @TIMEREMAINING@ @ @SPEED@ @ANIMDOTS@"` ...or something like that...

**Comment by shimon128** [comment]
Thank you very much.

**Comment by shimon128** [comment]
I have another question, if I may.
After I ran my file on a computer that has AVAST antivirus, it blocked it and wrote that the NScurl.DLL file inside the TEMP folder is a virus.
Is there anything to do with it
![AVAST](https://user-images.githubusercontent.com/70193333/187073214-b473b33b-91c8-4a45-82d2-886915fad610.PNG)
?

**Comment by negrutiu** [comment]
Hmm. That's unfortunate.
There must have been a temporary glitch in Avast's detection.
Check out https://www.virustotal.com/gui/file/e372463ff53d2ddfebd1871a269b7838e130473fd455247be4c56b517f70b873.
All major AV solutions (including Avast) report the file as clean.

**Comment by shimon128** [comment]
You're right, I found out why.
I use a DLL that is in the version of NSIS that you created (https://github.com/negrutiu/nsis) and there it is old and recognized as a virus.
What you have here on the other hand is newer and unrecognized.
I will replace and try again.

**Comment by shimon128** [comment]
I'm doing tests and suddenly I get a download error
"status: 0x57 parameter is incorrect" After I canceled the previous download to check that /RESUME does work well.
Any idea what this error means?

**Comment by negrutiu** [comment]
I ran some tests on my end and resuming looks fine here...
I used this call for testing:
```nsis
NScurl::http get "http://live.sysinternals.com/Files/SysinternalsSuite.zip" "$EXEDIR\_SysinternalsSuiteLive_SpeedCap.zip" /RESUME /CANCEL /INSIST /SPEEDCAP 307200 /END
```
Note: `/SPEEDCAP 307200` sets up a speed limit of 300kb/s. It's useful for testing in slow motion. Don't use it in production builds ;)
Can you try this with your URL and see what happens?
