### ISSUE TITLE
Could I use this plugin to sign and verify just like openssl？

### ISSUE THREAD

**Issue by BeyondIM** [negrutiu/nsis-nscurl#5]
Thank you for developing such a good plugin.  This plugin is built with openssl, could I use this plugin to sign and verify just like openssl？tks.

**Comment by negrutiu** [comment]
Sorry, that's not possible.
The plugin includes only a minimal set of `openssl` functions, required by `libcurl`.
Signing is not part of it.

**Comment by BeyondIM** [comment]
ok. tks.
